version: '3.8'

services:
  nats-server:
    image: nats:latest
    ports:
      - '8222:8222'

  #~> Client Gateway Microservice
  client_gateway:
    build: ./client_gateway
    ports:
      - ${CLIENT_GATEWAY_DOCKER_PORT}:${CLIENT_GATEWAY_PORT}
    volumes:
      - ./client_gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  #~> Auth Microservice
  auth_microservice:
    build: ./auth_microservice
    volumes:
      - ./auth_microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

  #~> Products Microservice
  products_microservice:
    build: ./products_microservice
    volumes:
      - ./products_microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

  #~> Orders Microservice
  orders_microservice:
    depends_on:
      - orders-db
    build: ./orders_microservice
    volumes:
      - ./orders_microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${ORDERS_MS_PORT}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  #~> Orders Database
  orders-db:
    container_name: orders_database
    image: postgres:latest
    restart: always
    volumes:
      - ./orders_microservice/postgres:/var/lib/postgresql/data
    ports:
      - ${ORDERS_DB_DOCKER_PORT}:${ORDERS_DB_PORT}
    environment:
      - POSTGRES_USER=${ORDERS_DB_USER}
      - POSTGRES_PASSWORD=${ORDERS_DB_PASSWORD}
      - POSTGRES_DB=${ORDERS_DB_NAME}

  #~> Payments Microservice
  payments_microservice:
    container_name: payments_microservice
    build: ./payments_microservice
    volumes:
      - ./payments_microservice/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
      - BASE_URL=${STRIPE_BASE_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}
